[build]
command = "pnpm --filter web codegen && pnpm --filter web build"
publish = "apps/web/dist"

[build.environment]
# GRAPHQL_SCHEMA_URL = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
