name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Typecheck & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      # - name: Test
      #   run: pnpm test

  build-and-deploy-api:
    name: Deploy API to Cloud Run
    needs: check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # For Workload Identity Federation

    env:
      GAR_LOCATION: us-central1
      REPOSITORY: wathiqah
      IMAGE_NAME: wathiqah-api
      API_PORT: 3001

    steps:
      - uses: actions/checkout@v4

      # 1. Authenticate to Google Cloud
      # You need to setup Workload Identity Federation or use a Service Account Key
      # See: https://github.com/google-github-actions/auth
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # 2. Setup Cloud SDK
      - uses: google-github-actions/setup-gcloud@v2

      # 3. Configure Docker
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # 4. Build Docker Image
      - name: Build Container
        run: |
          docker build \
            -f apps/api/Dockerfile \
            -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            .

      # 5. Push Docker Image
      - name: Push Container
        run: docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      # 6. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.IMAGE_NAME }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          region: us-central1
          env_vars: |
            NODE_ENV=production
            JWT_EXPIRATION=15m
            JWT_REFRESH_EXPIRATION=7d
            APP_NAME=Wathiqah
            APP_VERSION=1.0.0
            APP_URL=https://wathiqah.akanors.com
            API_PREFIX=api
            API_PORT=${{ env.API_PORT }}
            APP_EMAIL=wathiqah@akanors.com
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_DB=0
            MAILTRAP_TOKEN=${{ secrets.MAILTRAP_TOKEN }}
            EMAIL_FROM=${{ secrets.EMAIL_FROM }}
